### ISSUE TITLE
Windows: ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by swirlingsand** [hartwork/git-delete-merged-branches#16]
```
C:\Windows\system32>git-delete-merged-branches
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\git-delete-merged-branches.exe\__main__.py", line 4, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\git_delete_merged_branches\__main__.py", line 4, in <module>
    from ._cli import main
  File "c:\programdata\miniconda3\lib\site-packages\git_delete_merged_branches\_cli.py", line 17, in <module>
    from ._engine import DeleteMergedBranches
  File "c:\programdata\miniconda3\lib\site-packages\git_delete_merged_branches\_engine.py", line 10, in <module>
    from ._multiselect import multiselect
  File "c:\programdata\miniconda3\lib\site-packages\git_delete_merged_branches\_multiselect.py", line 4, in <module>
    from pick import Picker
  File "c:\programdata\miniconda3\lib\site-packages\pick\__init__.py", line 3, in <module>
    import curses
  File "c:\programdata\miniconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by hartwork** [comment]
Hi @swirlingsand , I have no way of testing this software on Windows myself but there is a chance that `pip install windows-curses` [makes things work](https://github.com/zephyrproject-rtos/windows-curses#background). Can you confirm?

**Comment by hartwork** [comment]
PS:
- To my current understanding it takes a curses module for Windows (e.g. `windows-curses`) and [enabling VT emulation on Windows](https://stackoverflow.com/a/51681675/11626624)
- https://github.com/wong2/pick/issues/15 could be of interest for alternatives to `windows-curses`
- Also, pick/curses is only used for interactive configuration. Let me know if I should write down how to bypass interactive configuration altogether, in case that's interesting to you.

**Comment by hartwork** [comment]
https://github.com/wong2/pick/pull/40 got merged now at pick upstream

**Comment by hartwork** [comment]
The [latest release 1.0.0 of pick at PyPI](https://pypi.org/project/pick/#history) is pulling in `windows-curses` by now. I'm closing this bug here as fixed; please feel free to re-open as needed.
