### ISSUE TITLE
`Error: not enough values to unpack (expected 2, got 1)`

### ISSUE THREAD

**Issue by ijoseph** [hartwork/git-delete-merged-branches#96]
Cannot use this on apparently any repository (trying on this one, for example):

```bash
╰─ git remote -v
origin  https://github.com/samuelmeuli/glance (fetch)
```

```bash
╰─ git-dmb
Error: not enough values to unpack (expected 2, got 1)
```

Environment: 
```
╰─ python3 --version
Python 3.10.8


╰─ neofetch
                    'c.          <redacted>
                 ,xNMM.          ----------------------------
               .OMMMMo           OS: macOS 12.5.1 21G83 arm64
               OMMM0,            Host: MacBookPro18,3
     .;loddo:' loolloddol;.      Kernel: 21.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 3 days, 5 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 241 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1800x3200, 1512x982
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1 Pro
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1 Pro
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 3021MiB / 16384MiB
       .cooc,.    .,coo:.
```

**Comment by hartwork** [comment]
Hi @ijoseph could you share the output of `git-dmb --version` and `git-dmb --debug`?

**Comment by ijoseph** [comment]
```bash
╰─ git-dmb --version
git-delete-merged-branches 7.2.0 
```

```python
╰─ git-dmb --debug
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/git_delete_merged_branches/_cli.py", line 157, in _inner_main
    _innermost_main(config, messenger)
  File "/opt/homebrew/lib/python3.10/site-packages/git_delete_merged_branches/_cli.py", line 132, in _innermost_main
    git_config = dmb.ensure_configured(config.force_reconfiguration)
  File "/opt/homebrew/lib/python3.10/site-packages/git_delete_merged_branches/_engine.py", line 150, in ensure_configured
    git_config = self._git.extract_git_config()
  File "/opt/homebrew/lib/python3.10/site-packages/git_delete_merged_branches/_git.py", line 86, in extract_git_config
    key, value = key_newline_value.split('\n', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Error: not enough values to unpack (expected 2, got 1) 
```

**Comment by ijoseph** [comment]
oh looks like it's mad about my `~/.gitconfig` for some reason 🤔

**Comment by ijoseph** [comment]
Not pretty, but here it is: 

```conf
# This is Git's per-user configuration file.
[user]
# Please adapt and uncomment the following lines:
	name = <REDACTED>
	email = <REDACTED>
	signingkey = <REDACTED>
[core]
	excludesfile = ~/.gitignore
	editor = emacs -nw
	pager = less -S
	trustctime = false
	pager = delta
[alias]
	lg = "log --color --graph --all --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commit"
	lgm = "log --color --graph  --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commit"
	notmaster = "log --color --graph   --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commit  --no-merges '^origin/master'"
	co = checkout
	br = branch -vv
	b = rev-parse --abbrev-ref HEAD
	sb = status -s -b
        sbd = status -s -b --ignore-submodules=dirty
	c = commit -a -m
	cm = commit -m
	ca = commit -a --amend --no-edit
	redo = commit -a --amend --no-edit
	cloner = clone --recursive
	dn = diff --name-only
	dnh = diff 'HEAD^' --name-only
	aa = add --all
	ss = submodule status
	df = submodule deinit -f .
	ui = submodule update --init
	sfgf = submodule foreach git fetch
	cc = rev-parse --short HEAD
	rt = rev-parse --abbrev-ref --symbolic-full-name @{u}
	conflicts = diff --name-only --diff-filter=U
	rc = rebase --continue
        dh = diff 'HEAD~1'
        sh = rev-parse --short
        rxo = rebase -Xours
        rxt = rebase -Xtheirs
        fom = fetch --prune origin master:master
        rsh = reset --hard
        tt = tag --points-at HEAD
        rom = rebase origin/master
        pom = pull origin master
        ds = diff --staged
        dhe = diff HEAD
        f = fetch --prune
        bp = describe --all @{-1} 
        nbfm = !git  checkout master && git pull origin master && git checkout -b ${1} && :
        nobs = log --reverse -S
        isa = merge-base --is-ancestor
        pt = pull --tags
        pn = !sh -c "git name-rev $(git rev-parse @{-1}) --name-only"  # previous branch _name_
        mbm = merge-base --fork-point master
	oldest-ancestor = !bash -c 'diff -u <(git rev-list --first-parent "${1:-master}") <(git rev-list --first-parent "${2:-HEAD}") | sed -ne \"s/^ //p\" | head -1' -
	ignored = !git ls-files -v $(git rev-parse --show-toplevel) | (grep '^[[:lower:]]' || echo 'None ignored.') && echo '\nIgnore changes with:   git update-index --assume-unchanged <file> \nor track again with:   git update-index --no-assume-unchanged <file>'
	shown = show --name-only
	dhr = diff 'HEAD@{1}'
	freshtags = fetch --tags --all --quiet --prune
	existremote = ls-remote --heads git@github.com:Affirm/all-the-things.git
	rh = reset --hard
	rs = reset --soft
	# bb: blame before	
	bb


#	update_master = fetch origin master:master
	

## cc: current commit
## rt: remote tracking (branch name)

# Only pull if no merge required; do this so can then rebase instead
[pull]
  ff = only

[diff]
	tool = opendiff

[diff "jupyternotebook"]
	command = git-nbdiffdriver diff
[merge "jupyternotebook"]
	driver = git-nbmergedriver merge %O %A %B %L %P
	name = jupyter notebook merge driver
[difftool "nbdime"]
	cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
[difftool]
	prompt = false
[mergetool "nbdime"]
	cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
	prompt = false
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[gpg]
	program = gpg

[delta]
    plus-style = "syntax #012800"
    minus-style = "syntax #340001"
    syntax-theme = Monokai Extended
    navigate = true
    side-by-side = true
    width = 250

[push]
	default = current
```

**Comment by hartwork** [comment]
Hi @ijoseph,

thanks for sharing that Git config of yours! :+1:  The troublemaker in there turned out to be `alias.bb` that lacks an assignment. My guess is that that can only be cause from manual editing and not from calls to `git config <name> <value>`.

It is unclear to me why Git is serving an arguably malformed entry(?) in `git config --list --null` output but I have prepared a fix to make git-delete-merged-branches robust towards those cases and to also produce warning-like output for those keys as well in pull request #97 now.

Any chance you could give the fix from the pull request a spin? One way to check the fixed version out would be something like:
```console
cd "$(mktemp -d)"
git clone --depth 1 --branch issue-96-be-rebust-towards-git-config-options-with-no-assignment https://github.com/hartwork/git-delete-merged-branches
cd git-delete-merged-branches/
pip install --user .
```

I can make a new release 7.2.1 containing this fix shortly after.

Best, Sebastian

**Comment by ijoseph** [comment]
Amazing turnaround; I’ll try to give it a look by the end of today, Pacific
time

**Comment by ijoseph** [comment]
Works great! 

```bash
╰─ git-delete-merged-branches
Git config option 'alias.bb' lacks assignment of a value.
Configure git-delete-merged-branches for repository 'glance':
[1/3] For a branch to be considered fully merged, which other branches must it have been merged to?

▶ [ ] master

(Press [Space] to toggle selection, [Enter]/[Return] to accept, [Ctrl]+[C] to quit.)
```

More info: 

Oh yeah, I see that invalid `bb` alias --  remember planning on making it, then I must have gotten distracted before filling it in. I even remember what I had intended to use it for. I'll just comment that line out for now, anyway. Interesting that it doesn't break `git` itself (I know that some things will in `.gitconfig`). 

> It is unclear to me why Git is serving an arguably malformed entry(?) in `git config --list --null output`

Yeah, very weird -- I think it's here in the last line FWIW. 

```bash
╰─ git config --list --null | grep -a  bb
log --color --graph --all --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commitalias.lgm
log --color --graph  --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commitalias.notmaster
log --color --graph   --pretty=format:'%C(auto)%h%Creset -%C(auto)%d%Creset %s %C(#f449ee)(%cr) %C(#f48d49)<%an>%C(reset)' --abbrev-commit  --no-merges '^origin/master'alias.co
rev-parse --abbrev-ref HEADalias.sb
rev-parse --abbrev-ref --symbolic-full-name @{u}alias.conflicts
reset --softalias.bbpull.ff
```

**Comment by hartwork** [comment]
@ijoseph thanks for testing, I have released 7.2.1 with the fix to PyPI just now.

**Comment by ijoseph** [comment]
Awesome, thanks for going above and beyond! A simple “fix your .gitconfig error” probably would have been totally fair tbh.

**Comment by hartwork** [comment]
@ijoseph I think it would only have been a matter of time until another user runs into it and it could also be argued that if we're parsing Git output we need to be rubust towards edge cases it may throw at us rather than crashing. I think it was the right call, and I'm glad I learned something. Thanks for the report! :pray:
